<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlantsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('plants')->insert([
            [
                'name' => 'Haricots verts',
                'type' => 'Légume vert',
                'sowing_period' => '04, 05, 06',
                'planting_period' => '05, 06, 07',
                'harvest_period' => '07, 08, 09',
                'soil' => 'Sol léger, bien drainé, riche en matière organique',
                'watering' => 'Arrosage régulier, sans excès, surtout pendant la floraison',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité, et butter les plants lorsqu\'ils atteignent 10-15 cm',
                'description' => 'Les haricots verts sont des légumes savoureux et croquants, parfaits pour des salades ou des plats cuisinés.',
                'image' => 'images/haricots_verts.jpg'
            ],
            [
                'name' => 'Courgettes',
                'type' => 'Courge',
                'sowing_period' => '04, 05',
                'planting_period' => '05, 06',
                'harvest_period' => '07, 08, 09, 10',
                'soil' => 'Sol riche en humus, profond et bien drainé',
                'watering' => 'Arrosage régulier, éviter de mouiller les feuilles',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Pailler pour maintenir l\'humidité et biner régulièrement',
                'description' => 'Les courgettes sont des légumes polyvalents qui peuvent être utilisés dans une variété de plats, des soupes aux grillades.',
                'image' => 'images/courgettes.webp'
            ],
            [
                'name' => 'Fraisier',
                'type' => 'Fruit rouge',
                'sowing_period' => '02, 03',
                'planting_period' => '03, 04',
                'harvest_period' => '06, 07',
                'soil' => 'Sol riche, frais, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide mais pas détrempé',
                'exposure' => 'Ensoleillée à mi-ombre',
                'maintenance' => 'Pailler, désherber régulièrement et retirer les stolons pour favoriser la production',
                'description' => 'Les fraisiers produisent des fraises juteuses et sucrées, idéales pour les desserts et les confitures.',
                'image' => 'images/fraisiers.jpg'
            ],
            [
                'name' => 'Framboisier',
                'type' => 'Fruit rouge',
                'sowing_period' => '03, 04',
                'planting_period' => '04, 05',
                'harvest_period' => '06, 07, 08, 09',
                'soil' => 'Sol riche en humus, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée à mi-ombre',
                'maintenance' => 'Tailler après la récolte et attacher les nouvelles pousses',
                'description' => 'Les framboisiers offrent des framboises délicieuses et nutritives, parfaites pour les collations et les desserts.',
                'image' => 'images/framboisiers.webp'
            ],
            [
                'name' => 'Aubergines',
                'type' => 'Légume',
                'sowing_period' => '02, 03',
                'planting_period' => '05, 06',
                'harvest_period' => '07, 08, 09',
                'soil' => 'Sol riche, profond, bien drainé',
                'watering' => 'Arrosage régulier, éviter de mouiller les feuilles',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Pailler pour maintenir l\'humidité et biner régulièrement',
                'description' => 'Les aubergines sont des légumes polyvalents, excellents pour les plats rôtis, grillés ou mijotés.',
                'image' => 'images/aubergines.jpg'
            ],
            [
                'name' => 'Butternut',
                'type' => "Courge",
                'sowing_period' => '04, 05',
                'planting_period' => '05, 06',
                'harvest_period' => '09, 10, 11',
                'soil' => 'Sol riche, profond, bien drainé',
                'watering' => 'Arrosage régulier, éviter de mouiller les feuilles',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Pailler pour maintenir l\'humidité et biner régulièrement',
                'description' => 'Les courges butternut sont sucrées et crémeuses, idéales pour les soupes et les purées.',
                'image' => 'images/butternut.jpg'
            ],
            [
                'name' => 'Carottes',
                'type' => 'Légume',
                'sowing_period' => '03, 04, 05',
                'planting_period' => '04, 05, 06',
                'harvest_period' => '07, 08, 09, 10',
                'soil' => 'Sol léger, profond, sableux, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Biner régulièrement, éclaircir les plants si nécessaire',
                'description' => 'Les carottes sont des légumes racines croquants, excellents crus ou cuits.',
                'image' => 'images/carottes.webp'
            ],
            [
                'name' => 'Endives',
                'type' => "Légume d'hiver",
                'sowing_period' => '05, 06',
                'planting_period' => '06, 07',
                'harvest_period' => '10, 11, 12',
                'soil' => 'Sol léger, riche en humus, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Pailler pour maintenir l\'humidité et biner régulièrement',
                'description' => 'Les endives, ou chicons, sont parfaites pour des salades fraîches ou cuites.',
                'image' => 'images/endives.jpg'
            ],
            [
                'name' => 'Laitues',
                'type' => 'Salade',
                'sowing_period' => '02, 03, 04',
                'planting_period' => '03, 04, 05',
                'harvest_period' => '05, 06, 07, 08',
                'soil' => 'Sol léger, riche en humus, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée à mi-ombre',
                'maintenance' => 'Pailler pour maintenir l\'humidité et biner régulièrement',
                'description' => 'Les laitues sont des légumes-feuilles croquants, idéals pour les salades.',
                'image' => 'images/laitues.jpg'
            ],
            [
                'name' => 'Mâche',
                'type' => 'Salade',
                'sowing_period' => '08, 09',
                'planting_period' => '09, 10',
                'harvest_period' => '11, 12, 01',
                'soil' => 'Sol léger, riche en humus, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Mi-ombre',
                'maintenance' => 'Pailler pour maintenir l\'humidité et biner régulièrement',
                'description' => 'La mâche est une salade d\'hiver douce et savoureuse.',
                'image' => 'images/mache.webp'
            ],
            [
                'name' => 'Poivrons',
                'type' => 'Légume',
                'sowing_period' => '02, 03',
                'planting_period' => '05, 06',
                'harvest_period' => '07, 08, 09',
                'soil' => 'Sol riche, profond, bien drainé',
                'watering' => 'Arrosage régulier, éviter de mouiller les feuilles',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Pailler pour maintenir l\'humidité et biner régulièrement',
                'description' => 'Les poivrons sont des légumes colorés et savoureux, parfaits pour des salades, des grillades ou des plats cuisinés.',
                'image' => 'images/poivrons.jpg'
            ],
            [
                'name' => 'Tomates',
                'type' => 'Légume',
                'sowing_period' => '02, 03, 04',
                'planting_period' => '05, 06',
                'harvest_period' => '07, 08, 09, 10',
                'soil' => 'Sol riche, profond, bien drainé',
                'watering' => 'Arrosage régulier, éviter de mouiller les feuilles',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Pailler pour maintenir l\'humidité, tuteurer les plants et enlever les gourmands',
                'description' => 'Les tomates sont des légumes incontournables, idéals pour les salades, les sauces et les plats cuisinés.',
                'image' => 'images/tomates.jpg'
            ],
            [
                'name' => 'Radis',
                'type' => 'Légume-racine',
                'sowing_period' => '03, 04, 05',
                'planting_period' => '04, 05, 06',
                'harvest_period' => '05, 06, 07, 08',
                'soil' => 'Sol léger, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Biner régulièrement, éclaircir les plants si nécessaire',
                'description' => 'Les radis sont des légumes-racines croquants et piquants, parfaits pour des salades ou en apéritif.',
                'image' => 'images/radis.jpeg'
            ],
            [
                'name' => 'Poireaux',
                'type' => 'Légume d\'hiver',
                'sowing_period' => '01, 02, 03',
                'planting_period' => '04, 05',
                'harvest_period' => '09, 10, 11, 12',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée à mi-ombre',
                'maintenance' => 'Biner régulièrement, butter les plants pour les blanchir',
                'description' => 'Les poireaux sont des légumes savoureux, parfaits pour les soupes et les plats mijotés.',
                'image' => 'images/poireaux.jpg'
            ],
            [
                'name' => 'Épinards',
                'type' => 'Légume-feuille',
                'sowing_period' => '02, 03, 04, 08, 09, 10',
                'planting_period' => '03, 04, 09, 10',
                'harvest_period' => '05, 06, 10, 11',
                'soil' => 'Sol riche en humus, frais, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée à mi-ombre',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'Les épinards sont des légumes-feuilles nutritifs, excellents pour les salades et les plats cuits.',
                'image' => 'images/epinards.jpg'
            ],
            [
                'name' => 'Melons',
                'type' => 'Fruit',
                'sowing_period' => '03, 04, 05',
                'planting_period' => '05, 06',
                'harvest_period' => '07, 08, 09',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, éviter de mouiller les feuilles',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Pailler pour maintenir l\'humidité, pincer les tiges pour favoriser la fructification',
                'description' => 'Les melons sont des fruits sucrés et juteux, parfaits pour les desserts et les salades de fruits.',
                'image' => 'images/melon.jpg'
            ],
            [
                'name' => 'Chou-fleur',
                'type' => 'Légume d\'hiver',
                'sowing_period' => '05, 06',
                'planting_period' => '07, 08',
                'harvest_period' => '10, 11, 12',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'Le chou-fleur est un légume savoureux, parfait pour les gratins et les soupes.',
                'image' => 'images/chou_fleur.jpg'
            ],
            [
                'name' => 'Chou rouge',
                'type' => 'Légume',
                'sowing_period' => '04, 05',
                'planting_period' => '06, 07',
                'harvest_period' => '09, 10, 11',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée à mi-ombre',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'Le chou rouge est un légume croquant, parfait pour les salades et les plats mijotés.',
                'image' => 'images/chou_rouge.jpg'
            ],
            [
                'name' => 'Betteraves',
                'type' => 'Légume-racine',
                'sowing_period' => '04, 05, 06',
                'planting_period' => '05, 06, 07',
                'harvest_period' => '07, 08, 09, 10',
                'soil' => 'Sol léger, riche en humus, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Biner régulièrement, éclaircir les plants si nécessaire',
                'description' => 'Les betteraves sont des légumes-racines sucrés, parfaits pour les salades et les plats cuits.',
                'image' => 'images/betteraves.jpg'
            ],
            [
                'name' => 'Blettes cardes',
                'type' => 'Légume-feuille',
                'sowing_period' => '03, 04, 05, 06',
                'planting_period' => '04, 05, 06, 07',
                'harvest_period' => '06, 07, 08, 09, 10',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée à mi-ombre',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'Les blettes cardes sont des légumes-feuilles polyvalents, parfaits pour les soupes et les gratins.',
                'image' => 'images/blettes_cardes.webp'
            ],
            [
                'name' => 'Céleri-rave',
                'type' => 'Légume-racine',
                'sowing_period' => '02, 03, 04',
                'planting_period' => '05, 06',
                'harvest_period' => '10, 11, 12',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'Le céleri-rave est un légume-racine savoureux, parfait pour les purées et les soupes.',
                'image' => 'images/celeri_rave.jpg'
            ],
            [
                'name' => 'Céleri-branche',
                'type' => 'Légume',
                'sowing_period' => '02, 03, 04',
                'planting_period' => '05, 06',
                'harvest_period' => '08, 09, 10',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée à mi-ombre',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'Le céleri-branche est un légume croquant, parfait pour les salades et les plats cuits.',
                'image' => 'images/celeri_branche.jpg'
            ],
            [
                'name' => 'Brocoli',
                'type' => 'Légume',
                'sowing_period' => '03, 04',
                'planting_period' => '05, 06',
                'harvest_period' => '08, 09, 10',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'Le brocoli est un légume nutritif, excellent pour les salades et les plats cuits.',
                'image' => 'images/brocoli.jpg'
            ],
            [
                'name' => 'Choux de Bruxelles',
                'type' => 'Légume',
                'sowing_period' => '03, 04, 05',
                'planting_period' => '06, 07',
                'harvest_period' => '10, 11, 12',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'Les choux de Bruxelles sont des légumes savoureux, parfaits pour les plats rôtis et les soupes.',
                'image' => 'images/choux_de_bruxelles.jpg'
            ],
            [
                'name' => 'Chou romanesco',
                'type' => 'Légume',
                'sowing_period' => '04, 05',
                'planting_period' => '06, 07',
                'harvest_period' => '09, 10, 11',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'Le chou romanesco est un légume croquant et savoureux, parfait pour les salades et les plats cuits.',
                'image' => 'images/chou_romanesco.jpg'
            ],
            [
                'name' => 'Chou kale',
                'type' => 'Légume-feuille',
                'sowing_period' => '03, 04, 05',
                'planting_period' => '06, 07',
                'harvest_period' => '09, 10, 11',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée à mi-ombre',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'Le chou kale est un légume-feuille nutritif, excellent pour les salades et les smoothies.',
                'image' => 'images/chou_kale.jpg'
            ],
            [
                'name' => 'Concombre',
                'type' => 'Légume',
                'sowing_period' => '04, 05',
                'planting_period' => '05, 06',
                'harvest_period' => '07, 08, 09',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, éviter de mouiller les feuilles',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Pailler pour maintenir l\'humidité, pincer les tiges pour favoriser la fructification',
                'description' => 'Les concombres sont des légumes croquants et rafraîchissants, parfaits pour les salades.',
                'image' => 'images/concombre.png'
            ],
            [
                'name' => 'Courge musquée',
                'type' => 'Courge',
                'sowing_period' => '04, 05',
                'planting_period' => '05, 06',
                'harvest_period' => '09, 10, 11',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, éviter de mouiller les feuilles',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Pailler pour maintenir l\'humidité, biner régulièrement',
                'description' => 'La courge musquée est un légume sucré et crémeux, idéal pour les soupes et les purées.',
                'image' => 'images/courge_musquee.jpg'
            ],
            [
                'name' => 'Courge spaghetti',
                'type' => 'Courge',
                'sowing_period' => '04, 05',
                'planting_period' => '05, 06',
                'harvest_period' => '09, 10, 11',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, éviter de mouiller les feuilles',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Pailler pour maintenir l\'humidité, biner régulièrement',
                'description' => 'La courge spaghetti est un légume unique dont la chair se transforme en filaments semblables à des spaghettis une fois cuite.',
                'image' => 'images/courge_spaghetti.jpg'
            ],
            [
                'name' => 'Fenouil',
                'type' => 'Légume',
                'sowing_period' => '04, 05, 06',
                'planting_period' => '06, 07',
                'harvest_period' => '08, 09, 10',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'Le fenouil est un légume aromatique, parfait pour les salades et les plats cuits.',
                'image' => 'images/fenouil.webp'
            ],
            [
                'name' => 'Haricots beurre',
                'type' => 'Légume',
                'sowing_period' => '05, 06, 07',
                'planting_period' => '06, 07',
                'harvest_period' => '07, 08, 09',
                'soil' => 'Sol léger, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'Les haricots beurre sont des légumes tendres et savoureux, parfaits pour les plats mijotés et les salades.',
                'image' => 'images/haricots_beurre.jpg'
            ],
            [
                'name' => 'Oignons',
                'type' => 'Légume',
                'sowing_period' => '02, 03, 04',
                'planting_period' => '03, 04, 05',
                'harvest_period' => '07, 08, 09',
                'soil' => 'Sol léger, bien drainé',
                'watering' => 'Arrosage régulier, éviter de mouiller les feuilles',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'Les oignons sont des légumes aromatiques essentiels pour de nombreuses recettes.',
                'image' => 'images/oignon.jpg'
            ],
            [
                'name' => 'Échalotes',
                'type' => 'Légume',
                'sowing_period' => '03, 04, 08, 09',
                'planting_period' => '04, 09, 10',
                'harvest_period' => '07, 08, 09',
                'soil' => 'Sol léger, bien drainé',
                'watering' => 'Arrosage modéré, éviter de mouiller les feuilles',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'Les échalotes sont des légumes aromatiques parfaits pour les sauces et les marinades.',
                'image' => 'images/echalote.jpg'
            ],
            [
                'name' => 'Ail',
                'type' => 'Légume',
                'sowing_period' => '10, 11',
                'planting_period' => '11, 12',
                'harvest_period' => '07, 08',
                'soil' => 'Sol léger, bien drainé',
                'watering' => 'Arrosage modéré, éviter de mouiller les feuilles',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'L\'ail est un légume aromatique essentiel pour de nombreuses recettes.',
                'image' => 'images/ail.webp'
            ],
            [
                'name' => 'Panais',
                'type' => 'Légume-racine',
                'sowing_period' => '03, 04, 05',
                'planting_period' => '04, 05, 06',
                'harvest_period' => '09, 10, 11',
                'soil' => 'Sol léger, riche en humus, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'Les panais sont des légumes-racines sucrés, parfaits pour les soupes et les plats rôtis.',
                'image' => 'images/panais.jpg'
            ],
            [
                'name' => 'Roquette',
                'type' => 'Salade',
                'sowing_period' => '03, 04, 05, 06, 08, 09, 10',
                'planting_period' => '04, 05, 08, 09',
                'harvest_period' => '05, 06, 07, 09, 10',
                'soil' => 'Sol léger, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée à mi-ombre',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'La roquette est un légume-feuille poivré, parfait pour les salades.',
                'image' => 'images/roquette.jpg'
            ],
            [
                'name' => 'Rhubarbe',
                'type' => 'Légume',
                'sowing_period' => '02, 03',
                'planting_period' => '03, 04',
                'harvest_period' => '05, 06, 07, 08, 09',
                'soil' => 'Sol riche, bien drainé',
                'watering' => 'Arrosage régulier, maintenir le sol humide',
                'exposure' => 'Ensoleillée à mi-ombre',
                'maintenance' => 'Biner régulièrement, pailler pour maintenir l\'humidité',
                'description' => 'La rhubarbe est un légume acidulé, parfait pour les tartes et les compotes.',
                'image' => 'images/rhubarbe.jpg'
            ],
        ]);
    }
}
